export const areas = [
  {
    id: "1-1",
    act: 1,
    name: {
      "zh-cn": "鲜红荒地、 邪恶洞窟",
    },
    immunities: ["f", "c"],
    tier: "F",
    "tier-exp": "F",
    "tier-loot": "F",
    areas: ["Blood_Moor", "Den_of_Evil"],
  },
  {
    id: "1-2",
    act: 1,
    name: {
      "zh-cn": "冰冷之原、洞穴",
    },
    immunities: ["f", "c", "l"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "D",
    areas: ["Cold_Plains", "Cave"],
  },
  {
    id: "1-3",
    act: 1,
    name: {
      "zh-cn": "埋骨之地、墓穴、大陵墓",
    },
    immunities: ["l"],
    tier: "F",
    "tier-exp": "F",
    "tier-loot": "F",
    areas: ["Burial_Grounds", "Crypt", "Mausoleum"],
  },
  {
    id: "1-4",
    act: 1,
    name: {
      "zh-cn": "石块旷野",
    },
    immunities: ["f", "c", "l", "p"],
    tier: "F",
    "tier-exp": "F",
    "tier-loot": "D",
    areas: ["Stony_Field"],
  },
  {
    id: "1-5",
    act: 1,
    name: {
      "zh-cn": "崔斯特姆",
    },
    immunities: ["f", "l", "p"],
    tier: "F",
    "tier-exp": "F",
    "tier-loot": "F",
    areas: ["Tristram"],
  },
  {
    id: "1-6",
    act: 1,
    name: {
      "zh-cn": "黑暗森林、地底通道",
    },
    immunities: ["f", "c", "l", "p"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "D",
    areas: ["Dark_Wood", "Underground_Passage"],
  },
  {
    id: "1-7",
    act: 1,
    name: {
      "zh-cn": "黑色沼泽、 地洞",
    },
    immunities: ["f", "c", "l", "p"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "D",
    areas: ["Black_Marsh", "Hole"],
  },
  {
    id: "1-8",
    act: 1,
    name: {
      "zh-cn": "遗忘之塔",
    },
    immunities: ["f", "c", "l", "ph"],
    tier: "B",
    "tier-exp": "C",
    "tier-loot": "A",
    areas: ["Forgotten_Tower"],
  },
  {
    id: "1-9",
    act: 1,
    name: {
      "zh-cn": "深坑",
    },
    immunities: ["f", "c", "l"],
    tier: "A",
    "tier-exp": "A",
    "tier-loot": "A",
    areas: ["Pit"],
  },
  {
    id: "1-10",
    act: 1,
    name: {
      "zh-cn": "监狱、营房",
    },
    immunities: ["f", "c", "l", "p", "ph"],
    tier: "B",
    "tier-exp": "B",
    "tier-loot": "C",
    areas: ["Jail", "Barracks"],
  },
  {
    id: "1-11",
    act: 1,
    name: {
      "zh-cn": "大教堂、地下墓穴",
    },
    immunities: ["f", "c", "l", "ph"],
    tier: "A",
    "tier-exp": "A",
    "tier-loot": "A",
    areas: ["Cathedral", "Catacombs"],
  },
  {
    id: "1-12",
    act: 1,
    name: {
      "zh-cn": "神秘的奶牛关",
    },
    immunities: [],
    tier: "B",
    "tier-exp": "B",
    "tier-loot": "S",
    areas: ["Secret_Cow_Level"],
  },
  {
    id: "1-13",
    act: 1,
    name: {
      "zh-cn": "监狱",
    },
    immunities: ["f", "l", "p", "ph"],
    tier: "B",
    "tier-exp": "B",
    "tier-loot": "C",
    areas: ["Jail"],
  },
  {
    id: "2-1",
    act: 2,
    name: {
      "zh-cn": "鲁高因下水道",
    },
    immunities: ["f", "p"],
    tier: "B",
    "tier-exp": "B",
    "tier-loot": "C",
    areas: ["Lut_Gholein_Sewers"],
  },
  {
    id: "2-2",
    act: 2,
    name: {
      "zh-cn": "碎石荒野、碎石古墓",
    },
    immunities: ["f", "c", "l", "p"],
    tier: "B",
    "tier-exp": "B",
    "tier-loot": "C",
    areas: ["Rocky_Waste", "Stony_Tomb"],
  },
  {
    id: "2-3",
    act: 2,
    name: {
      "zh-cn": "干燥高地、亡者大殿",
    },
    immunities: ["f", "c", "l", "p"],
    tier: "B",
    "tier-exp": "A",
    "tier-loot": "C",
    areas: ["Dry_Hills", "Halls_of_the_Dead"],
  },
  {
    id: "2-4",
    act: 2,
    name: {
      "zh-cn": "偏远绿洲",
    },
    immunities: ["l", "p", "ph"],
    tier: "F",
    "tier-exp": "F",
    "tier-loot": "F",
    areas: ["Far_Oasis"],
  },
  {
    id: "2-5",
    act: 2,
    name: {
      "zh-cn": "古代水道",
    },
    immunities: ["f", "l", "p", "m"],
    tier: "D",
    "tier-exp": "D",
    "tier-loot": "C",
    areas: ["Ancient_Tunnels"],
  },
  {
    id: "2-6",
    act: 2,
    name: {
      "zh-cn": "失落之城、群蛇峡谷、利爪蝮蛇神殿",
    },
    immunities: ["f", "c", "l", "p", "m"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "C",
    areas: ["Lost_City", "Valley_of_Snakes", "Claw_Viper_Temple"],
  },
  {
    id: "2-7",
    act: 2,
    name: {
      "zh-cn": "神秘避难所",
    },
    immunities: ["f", "c", "l", "p", "ph"],
    tier: "B",
    "tier-exp": "C",
    "tier-loot": "A",
    areas: ["Arcane_Sanctuary"],
  },
  {
    id: "2-8",
    act: 2,
    name: {
      "zh-cn": "塔拉夏的古墓、塔拉夏的密室",
    },
    immunities: ["f", "c", "l", "p", "ph", "m"],
    tier: "S",
    "tier-exp": "S",
    "tier-loot": "A",
    areas: ["Tal_Rashas_Tomb", "Tal_Rashas_Chamber"],
  },
  {
    id: "3-1",
    act: 3,
    name: {
      "zh-cn": "蜘蛛森林、蜘蛛洞穴",
    },
    immunities: ["f", "c", "l", "p"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "B",
    areas: ["Spider_Forest", "Spider_Cavern"],
  },
  {
    id: "3-2",
    act: 3,
    name: {
      "zh-cn": "翠绿丛林、翠绿监牢",
    },
    immunities: ["f", "c", "l", "p", "ph"],
    tier: "A",
    "tier-exp": "A",
    "tier-loot": "B",
    areas: ["Flayer_Jungle", "Flayer_Dungeon"],
  },
  {
    id: "3-3",
    act: 3,
    name: {
      "zh-cn": "庞大湿地",
    },
    immunities: ["f", "c", "l"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "B",
    areas: ["Great_Marsh"],
  },
  {
    id: "3-4",
    act: 3,
    name: {
      "zh-cn": "库拉斯特市集、毁灭的神庙、废弃的礼拜堂",
    },
    immunities: ["f", "c", "ph", "m"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "B",
    areas: ["Kurast_Bazaar", "Ruined_Temple", "Disused_Fane"],
  },
  {
    id: "3-5",
    act: 3,
    name: {
      "zh-cn": "崔凡克",
    },
    immunities: ["f", "c", "l"],
    tier: "B",
    "tier-exp": "B",
    "tier-loot": "A",
    areas: ["Travincal"],
  },
  {
    id: "3-6",
    act: 3,
    name: {
      "zh-cn": "憎恨囚牢",
    },
    immunities: ["c", "l", "p"],
    tier: "B",
    "tier-exp": "C",
    "tier-loot": "A",
    areas: ["Durance_of_Hate"],
  },
  {
    id: "3-7",
    act: 3,
    name: {
      "zh-cn": "库拉斯特下水道",
    },
    immunities: ["c", "p", "m"],
    tier: "D",
    "tier-exp": "D",
    "tier-loot": "D",
    areas: ["Kurast_Sewers"],
  },
  {
    id: "4-1",
    act: 4,
    name: {
      "zh-cn": "外域荒原、绝望平原",
    },
    immunities: ["f", "c", "l", "p"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "C",
    areas: ["Outer_Steppes", "Plains_of_Despair"],
  },
  {
    id: "4-2",
    act: 4,
    name: {
      "zh-cn": "火焰之河、罪罚之城",
    },
    immunities: ["f", "c", "l", "p"],
    tier: "B",
    "tier-exp": "B",
    "tier-loot": "B",
    areas: ["River_of_Flame", "City_of_the_Damned"],
  },
  {
    id: "4-3",
    act: 4,
    name: {
      "zh-cn": "混沌避难所",
    },
    immunities: ["f", "c", "l", "p"],
    tier: "S",
    "tier-exp": "S",
    "tier-loot": "S",
    areas: ["Chaos_Sanctuary"],
  },
  {
    id: "5-1",
    act: 5,
    name: {
      "zh-cn": "苦战丘陵、冰冻高地、亚巴顿",
    },
    immunities: ["f", "c", "l", "p", "ph"],
    tier: "B",
    "tier-exp": "B",
    "tier-loot": "B",
    areas: ["Bloody_Foothills", "Frigid_Highlands", "Abaddon"],
  },
  {
    id: "5-2",
    act: 5,
    name: {
      "zh-cn": "冰河小径、漂流洞窟",
    },
    immunities: ["f", "c", "l", "p", "ph"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "C",
    areas: ["Glacial_Trail", "Drifter_Cavern"],
  },
  {
    id: "5-3",
    act: 5,
    name: {
      "zh-cn": "先祖之路、寒冰地窖",
    },
    immunities: ["c", "l", "p", "ph"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "C",
    areas: ["Ancients_Way", "Icy_Cellar"],
  },
  {
    id: "5-4",
    act: 5,
    name: {
      "zh-cn": "亚瑞特高原、阿克隆深渊",
    },
    immunities: ["f", "c", "l", "p", "ph", "m"],
    tier: "B",
    "tier-exp": "B",
    "tier-loot": "C",
    areas: ["Arreat_Plateau", "Pit_of_Acheron"],
  },
  {
    id: "5-5",
    act: 5,
    name: {
      "zh-cn": "水晶通道、冰冻之河",
    },
    immunities: ["f", "c", "l", "p", "ph"],
    tier: "C",
    "tier-exp": "C",
    "tier-loot": "C",
    areas: ["Crystalline_Passage", "Frozen_River"],
  },
  {
    id: "5-6",
    act: 5,
    name: {
      "zh-cn": "尼拉塞克神殿、痛楚大厅、苦痛大厅、沃特大厅",
    },
    immunities: ["f", "c", "l", "p", "ph"],
    tier: "A",
    "tier-exp": "B",
    "tier-loot": "A",
    areas: [
      "Nihlathaks_Temple",
      "Halls_of_Anguish",
      "Halls_of_Pain",
      "Halls_of_Vaught",
    ],
  },
  {
    id: "5-7",
    act: 5,
    name: {
      "zh-cn": "世界之石要塞、毁灭王座、世界之石大殿",
    },
    immunities: ["f", "c", "l", "p", "ph", "m"],
    tier: "S",
    "tier-exp": "S",
    "tier-loot": "S",
    areas: ["Worldstone_Keep", "Throne_of_Destruction", "Worldstone_Chamber"],
  },
  {
    id: "5-8",
    act: 5,
    name: {
      "zh-cn": "冰冻高地",
    },
    immunities: ["f", "c", "l", "p"],
    tier: "B",
    "tier-exp": "B",
    "tier-loot": "B",
    areas: ["Frigid_Highlands"],
  },
];
